### ISSUE TITLE
Release notes not up to date.  

### ISSUE THREAD

**Issue by joshbooker** [MicrosoftDocs/OfficeDocs-ProjectServer#133] opened 2021-11-10 16:12 UTC
My environment says version 1.0.14.98 of this solution is installed and an update is available having version 1.0.25.91  Why is this doc so far behind and where do we go to see what's new?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a801175-de35-1beb-b061-f87d8ff1ef94
* Version Independent ID: 943295ec-36af-81f2-869f-6478228c41d4
* Content: [Project Service Core solution version history - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/project-service-core-solution-version-history)
* Content Source: [ProjectWeb/project-service-core-solution-version-history.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/project-service-core-solution-version-history.md)
* Service: **project-web**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by tiburd** [comment] 2023-02-22 16:37
Duplicate of #120 . 
Closing issue.

**Closed by tiburd** 2023-02-22 16:37 UTC
Labels: duplicate
